#!/usr/bin/env python3
"""
Quick Start Setup Script for Photo Proof Backend
Automates environment setup, database seeding, and validation.
"""

import os
import sys
import secrets
from pathlib import Path


def print_header(text):
    """Print formatted section header."""
    print(f"\n{'='*60}")
    print(f"  {text}")
    print(f"{'='*60}\n")


def generate_secret_key():
    """Generate secure SECRET_KEY."""
    return secrets.token_urlsafe(32)


def create_env_file():
    """Create .env file if it doesn't exist."""
    print_header("1. Environment Configuration")
    
    env_path = Path(__file__).parent / ".env"
    
    if env_path.exists():
        print(f"✅ .env file already exists: {env_path}")
        return
    
    secret_key = generate_secret_key()
    
    env_content = f"""# Photo Proof API Configuration
# Generated by quickstart.py

# Database
DATABASE_URL=sqlite:///./photo_proof.db
# For production: DATABASE_URL=postgresql://user:password@localhost/photo_proof

# Security (CHANGE IN PRODUCTION!)
SECRET_KEY={secret_key}
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=1440

# Storage
USE_S3=false
UPLOAD_DIR={Path(__file__).parent / 'uploads'}
MAX_UPLOAD_SIZE=10485760

# CORS
CORS_ORIGINS=http://localhost:5173,http://localhost:3000

# Environment
ENVIRONMENT=development
"""
    
    with open(env_path, "w") as f:
        f.write(env_content)
    
    print(f"✅ Created .env file: {env_path}")
    print(f"🔑 Generated SECRET_KEY: {secret_key[:20]}...")


def update_auth_service():
    """Update auth_service.py to read from environment."""
    print_header("2. Updating Auth Service")
    
    auth_service_path = Path(__file__).parent / "app" / "services" / "auth_service.py"
    
    if not auth_service_path.exists():
        print(f"⚠️  Auth service not found: {auth_service_path}")
        return
    
    with open(auth_service_path, "r") as f:
        content = f.read()
    
    # Check if already updated
    if "load_dotenv()" in content:
        print("✅ Auth service already configured for environment variables")
        return
    
    # Update imports and configuration
    old_imports = 'from jose import JWTError, jwt'
    new_imports = '''from jose import JWTError, jwt
import os
from dotenv import load_dotenv

load_dotenv()'''
    
    old_config = '''# Configuration
SECRET_KEY = "YOUR_SECRET_KEY_HERE"  # TODO: Move to environment variables
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24  # 24 hours'''
    
    new_config = '''# Configuration from environment
SECRET_KEY = os.getenv("SECRET_KEY", "YOUR_SECRET_KEY_HERE")
ALGORITHM = os.getenv("ALGORITHM", "HS256")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", "1440"))'''
    
    content = content.replace(old_imports, new_imports)
    content = content.replace(old_config, new_config)
    
    with open(auth_service_path, "w") as f:
        f.write(content)
    
    print(f"✅ Updated auth service to read from environment")


def create_seed_script():
    """Create database seed script."""
    print_header("3. Creating Seed Script")
    
    seed_path = Path(__file__).parent / "seed_data.py"
    
    if seed_path.exists():
        print(f"✅ Seed script already exists: {seed_path}")
        return
    
    seed_content = '''"""Seed database with initial data."""

from app.db.session import SessionLocal
from app.db.models import Studio, LayoutTemplate, Product, ServicePackage
from app.services.auth_service import AuthService
from decimal import Decimal
import json


def seed_database():
    """Populate database with demo data."""
    db = SessionLocal()
    
    try:
        print("🌱 Seeding database...")
        
        # 1. Create demo studio
        existing_studio = db.query(Studio).filter(Studio.email == "studio@photoproof.com").first()
        if not existing_studio:
            studio = Studio(
                id="studio_demo",
                studio_name="Demo Photography Studio",
                email="studio@photoproof.com",
                password_hash=AuthService.hash_password("password123"),
                logo="/uploads/default/logo.png",
            )
            db.add(studio)
            print("  ✅ Created demo studio user")
        else:
            print("  ℹ️  Demo studio already exists")
        
        # 2. Seed layout templates
        layouts = [
            {"id": "layout1", "name": "Classic Grid", "config": {"type": "grid", "columns": 3}},
            {"id": "layout2", "name": "Masonry", "config": {"type": "masonry", "columns": 4}},
            {"id": "layout3", "name": "Carousel", "config": {"type": "carousel"}},
            {"id": "layout4", "name": "Full Width", "config": {"type": "fullwidth"}},
            {"id": "layout5", "name": "Polaroid", "config": {"type": "polaroid", "columns": 3}},
            {"id": "layout6", "name": "Magazine", "config": {"type": "magazine"}},
            {"id": "layout7", "name": "Split Screen", "config": {"type": "split"}},
            {"id": "layout8", "name": "Collage", "config": {"type": "collage"}},
            {"id": "layout9", "name": "Timeline", "config": {"type": "timeline"}},
        ]
        
        layout_count = 0
        for layout_data in layouts:
            existing = db.query(LayoutTemplate).filter(LayoutTemplate.id == layout_data["id"]).first()
            if not existing:
                layout = LayoutTemplate(
                    id=layout_data["id"],
                    name=layout_data["name"],
                    layout_config=json.dumps(layout_data["config"]),
                )
                db.add(layout)
                layout_count += 1
        
        if layout_count > 0:
            print(f"  ✅ Created {layout_count} layout templates")
        else:
            print("  ℹ️  Layout templates already exist")
        
        # 3. Seed products
        products = [
            {
                "name": "8x10 Print",
                "description": "Professional quality 8x10 inch print",
                "price": Decimal("15.00"),
                "category": "Prints",
                "stock": 100,
            },
            {
                "name": "Canvas Print 16x20",
                "description": "Gallery-wrapped canvas print",
                "price": Decimal("89.00"),
                "category": "Canvas",
                "stock": 50,
            },
            {
                "name": "Photo Book - 20 pages",
                "description": "Hardcover photo book",
                "price": Decimal("49.00"),
                "category": "Albums",
                "stock": 30,
            },
        ]
        
        product_count = 0
        for product_data in products:
            existing = db.query(Product).filter(Product.name == product_data["name"]).first()
            if not existing:
                product = Product(
                    studio_id="studio_demo",
                    name=product_data["name"],
                    description=product_data["description"],
                    price=product_data["price"],
                    category=product_data["category"],
                    image="/api/placeholder/400/300",
                    stock=product_data["stock"],
                    product_options=json.dumps([]),
                )
                db.add(product)
                product_count += 1
        
        if product_count > 0:
            print(f"  ✅ Created {product_count} products")
        else:
            print("  ℹ️  Products already exist")
        
        # 4. Seed service packages
        packages = [
            {
                "id": "basic",
                "name": "Basic Package",
                "description": "Essential photography package",
                "price": Decimal("299.00"),
            },
            {
                "id": "premium",
                "name": "Premium Package",
                "description": "Complete photography experience",
                "price": Decimal("599.00"),
            },
        ]
        
        package_count = 0
        for package_data in packages:
            existing = db.query(ServicePackage).filter(ServicePackage.id == package_data["id"]).first()
            if not existing:
                package = ServicePackage(
                    id=package_data["id"],
                    studio_id="studio_demo",
                    name=package_data["name"],
                    description=package_data["description"],
                    price=package_data["price"],
                    package_features=json.dumps([]),
                    deliverables=json.dumps([]),
                )
                db.add(package)
                package_count += 1
        
        if package_count > 0:
            print(f"  ✅ Created {package_count} service packages")
        else:
            print("  ℹ️  Service packages already exist")
        
        db.commit()
        
        print("\\n🎉 Database seeding complete!")
        print("\\n📝 Demo Credentials:")
        print("   Email: studio@photoproof.com")
        print("   Password: password123")
        
    except Exception as e:
        db.rollback()
        print(f"\\n❌ Seeding failed: {str(e)}")
        raise
    
    finally:
        db.close()


if __name__ == "__main__":
    seed_database()
'''
    
    with open(seed_path, "w") as f:
        f.write(seed_content)
    
    print(f"✅ Created seed script: {seed_path}")


def run_seed_script():
    """Execute seed script."""
    print_header("4. Seeding Database")
    
    seed_path = Path(__file__).parent / "seed_data.py"
    
    if not seed_path.exists():
        print("⚠️  Seed script not found")
        return
    
    print("Running seed script...")
    os.system(f"python {seed_path}")


def validate_setup():
    """Validate that all required files exist."""
    print_header("5. Validating Setup")
    
    base_path = Path(__file__).parent
    
    checks = [
        (".env", "Environment configuration"),
        ("app/services/auth_service.py", "Auth service"),
        ("app/routers/auth.py", "Auth router"),
        ("app/routers/upload.py", "Upload router"),
        ("app/routers/comments.py", "Comments router"),
        ("app/routers/projects_template.py", "Template router"),
        ("seed_data.py", "Seed script"),
    ]
    
    all_valid = True
    for file_path, description in checks:
        full_path = base_path / file_path
        if full_path.exists():
            print(f"  ✅ {description}: {file_path}")
        else:
            print(f"  ❌ {description}: {file_path} NOT FOUND")
            all_valid = False
    
    return all_valid


def print_next_steps():
    """Print next steps for user."""
    print_header("🚀 Next Steps")
    
    print("""
1. Start the backend server:
   cd /Users/ns632@apac.comcast.com/Documents/v0_photo_proof/photo_proof_api
   source venv/bin/activate
   uvicorn app.main:app --reload

2. Test the API:
   Visit: http://localhost:8000/docs

3. Test authentication:
   Email: studio@photoproof.com
   Password: password123

4. Wire new routers into API:
   Edit: app/api/router.py
   Add: from app.routers import auth as new_auth, upload as new_upload, comments as new_comments
   Add: api_router.include_router(new_auth.router, prefix="/v2")

5. Integrate with frontend:
   See: BACKEND_INTEGRATION_GUIDE.md (Section 4)

6. Implement remaining routers:
   Use: app/routers/projects_template.py as reference
   Priority: photos → clients → folders → store → invoices → analytics

📚 Documentation:
   - Integration Guide: BACKEND_INTEGRATION_GUIDE.md
   - API Reference: API_ENDPOINTS_REFERENCE.md
   - Delivery Summary: DELIVERY_SUMMARY.md
""")


def main():
    """Main setup function."""
    print_header("Photo Proof Backend - Quick Start Setup")
    
    print("This script will:")
    print("  1. Create .env file with secure SECRET_KEY")
    print("  2. Update auth service to read from environment")
    print("  3. Create database seed script")
    print("  4. Seed database with demo data")
    print("  5. Validate setup")
    
    response = input("\n Continue? (y/n): ")
    if response.lower() != 'y':
        print("Setup cancelled.")
        return
    
    try:
        # Execute setup steps
        create_env_file()
        update_auth_service()
        create_seed_script()
        run_seed_script()
        
        # Validate
        if validate_setup():
            print_next_steps()
        else:
            print("\n⚠️  Some files are missing. Please check the output above.")
    
    except Exception as e:
        print(f"\n❌ Setup failed: {str(e)}")
        sys.exit(1)


if __name__ == "__main__":
    main()
